packages:
  - 'packages/*'
catalog:
  typescript: 5.1.3
  ts-node: ^10.9.1
  esbuild: ^0.17.19
  turbo: ^1.10.1
  prettier: ^2.8.8
  rimraf: ^5.0.1
  npm-run-all: ^4.1.5
  '@types/jest': ^29.5.2
  jest: ^29.5.0
  ts-jest: ^29.1.0
